In [2]:
import numpy as np

Zadanie 1 — po sekcji 1: Czym jest NumPy i dlaczego jest kluczowy¶

Masz listę cen produktów w sklepie: [120, 45, 300, 75, 60, 200].

Stwórz tablicę NumPy z tych cen, a następnie policz, ile kosztowałyby te produkty po podwyżce o 8% (bez użycia pętli — tylko operacja wektorowa). Wypisz wynik zaokrąglony do 2 miejsc po przecinku.

In [12]:
produkty = np.array([120, 45, 300, 75, 60, 200])

po_wzroscie = produkty * 1.08
po_wzroscie_zaokraglone = np.round(po_wzroscie, 2)

print(f"Ceny po podwyżce: {po_wzroscie_zaokraglone}")

Ceny po podwyżce: [129.6  48.6 324.   81.   64.8 216. ]


---

## Zadanie 2 — po sekcji 2: Indeksowanie i slicing

Dana jest tablica wyników sprzedaży tygodniowej (7 dni) dla 3 produktów:

```python

sales = np.array([

    [12, 15, 9, 20, 18, 25, 30],   # Produkt A

    [5,  7, 10, 12,  9, 14, 11],   # Produkt B

    [22, 18, 25, 30, 28, 35, 40],  # Produkt C

])

```

a) Wyciągnij sprzedaż Produktu B w ostatnie 3 dni tygodnia.

b) Korzystając z **boolean indexing**, wyciągnij wszystkie wartości sprzedaży większe niż 20

(z całej tablicy).

c) Zwróć sprzedaż w weekend (dni o indeksach 5 i 6) dla wszystkich produktów.


In [20]:
sales = np.array([
    [12, 15, 9, 20, 18, 25, 30],   # Produkt A
    [5,  7, 10, 12,  9, 14, 11],   # Produkt B
    [22, 18, 25, 30, 28, 35, 40],  # Produkt C
])

# a) Sprzedaż Produktu B w ostatnie 3 dni tygodnia
sales_b_last_3_days = sales[1, -3:]

# b) Wszystkie wartości sprzedaży większe niż 20
sales_above_20 = sales[sales > 20]

# c) Sprzedaż w weekend (dni o indeksach 5 i 6) dla wszystkich produktów
sales_on_weekend = sales[:, 5:]

print(f"""
a) Sprzedaż Produktu B w ostatnie 3 dni tygodnia: {sales_b_last_3_days}
b) Wszystkie wartości ponad 20: {sales_above_20}
c) Sprzedaż w weekend: {sales_on_weekend}""")


a) Sprzedaż Produktu B w ostatnie 3 dni tygodnia: [ 9 14 11]
b) Wszystkie wartości ponad 20: [25 30 22 25 30 28 35 40]
c) Sprzedaż w weekend: [[25 30]
 [14 11]
 [35 40]]


---

## Zadanie 3: Operacje wektorowe i ufuncs

Masz wyniki testów 4 studentów z 5 przedmiotów:

```python

grades = np.array([

    [80, 75, 90, 60, 85],

    [55, 60, 70, 65, 50],

    [95, 90, 88, 92, 97],

    [40, 45, 38, 50, 42],

])

```

a) Policz średnią ocenę każdego studenta (per wiersz).

b) Policz średnią z każdego przedmiotu (per kolumna).

c) Znajdź indeks studenta z najwyższą średnią (`argmax`).

d) Użyj `np.clip`, żeby "podnieść" wszystkie oceny niższe niż 45 do poziomu 45

(próg zaliczenia).






In [28]:
np.set_printoptions(formatter={'float_kind': '{:.2f}'.format})

grades = np.array([
    [80, 75, 90, 60, 85],
    [55, 60, 70, 65, 50],
    [95, 90, 88, 92, 97],
    [40, 45, 38, 50, 42],
])

# a) Średnia ocen każdego studenta (per wiersz)
avg = np.mean(grades, axis=1)

# b) Średnia z każdego przedmiotu (per kolumna)
avg_per_subject = np.mean(grades, axis=0)

# c) Indeks studenta z najwyższą średnią
idx_best_student = np.argmax(avg)

# d) Podniesienie wszystkich ocen niższych niż 45 do poziomu 45
grades_clipped = np.clip(grades, 45, None)

print(f"""
a) Średnia ocen każdego studenta: {avg}
b) Średnia z każdego przedmiotu: {avg_per_subject}
c) Indeks studenta z najwyższą średnią: {idx_best_student}
d) Oceny po podniesieniu do poziomu 45:
{grades_clipped}""")


a) Średnia ocen każdego studenta: [78.00 60.00 92.40 43.00]
b) Średnia z każdego przedmiotu: [67.50 67.50 71.50 66.75 68.50]
c) Indeks studenta z najwyższą średnią: 2
d) Oceny po podniesieniu do poziomu 45: 
[[80 75 90 60 85]
 [55 60 70 65 50]
 [95 90 88 92 97]
 [45 45 45 50 45]]
