# ✅ Lekcja 10 — Zadania numpy
Komplet rozwiązań 20 zadań. Każde rozwiązanie jest **uruchamialne**. Tam, gdzie zadanie
korzysta z losowości, ustawiamy `seed` dla powtarzalności (zgodnie z treścią lub dla wygody).



In [8]:
import numpy as np
import matplotlib.pyplot as plt
import time
%matplotlib inline
print("NumPy", np.__version__)
np.set_printoptions(formatter={'float_kind': '{:.2f}'.format})


NumPy 2.4.6


## ✏️ Zadania podstawowe (1–8)

### Zadanie 1 — Tworzenie i analiza tablic

Utwórz tablicę NumPy zawierającą liczby od 1 do 100. Oblicz i wypisz:
- Sumę wszystkich elementów
- Średnią arytmetyczną
- Medianę
- Wartość maksymalną i minimalną

**Wymagania:**
- Użyj `np.arange()` do stworzenia tablicy
- Użyj funkcji agregujących NumPy (`np.sum`, `np.mean`, etc.)

*(proste)*

### Zadanie 2 — Operacje wektorowe

Masz dwie tablice reprezentujące ceny produktów przed i po rabacie:
```python
before = np.array([100, 250, 75, 320, 180, 450, 90])
after = np.array([80, 200, 60, 280, 150, 400, 75])
```

Oblicz i wypisz:
- Różnicę między cenami (oszczędności)
- Procent rabatu dla każdego produktu
- Średnią oszczędność

**Wymagania:**
- Użyj operacji wektorowych (bez pętli)
- Wynik zaokrąglij do 2 miejsc po przecinku

*(proste)*

### Zadanie 3 — Indeksowanie i slicing

Dana tablica 1D:
```python
temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])
```

Wykonaj:
- Wypisz temperatury z dni parzystych (0, 2, 4, ...)
- Wypisz ostatnie 5 temperatur
- Wypisz temperatury w odwrotnej kolejności
- Znajdź temperatury większe niż 20

*(proste)*

### Zadanie 4 — Tablice 2D

Utwórz tablicę 2D (5x4) wypełnioną losowymi liczbami całkowitymi od 1 do 50.

**Wymagania:**
- Użyj `np.random.randint()`
- Wypisz shape tablicy
- Wypisz drugi wiersz
- Wypisz trzecią kolumnę
- Wypisz element z pozycji (2, 3)

*(proste)*

### Zadanie 5 — Statystyki per wiersz i kolumna

Dana tablica reprezentująca sprzedaż 4 produktów w 7 dni:
```python
sales = np.random.randint(10, 100, size=(4, 7))
```

Oblicz i wypisz:
- Średnią sprzedaż per produkt (axis=1)
- Średnią sprzedaż per dzień (axis=0)
- Dzień z najwyższą sprzedażą (np.argmax)
- Produkt z najniższą średnią sprzedażą

*(proste)*

### Zadanie 6 — Boolean indexing

Masz tablicę z oceną studentów:
```python
grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])
```

Wykonaj:
- Znajdź wszystkie oceny >= 80 (oceny wysokie)
- Znajdź wszystkie oceny < 50 (oceny niedostateczne)
- Policz ile jest ocen w przedziale [60, 80)
- Zmień wszystkie oceny < 50 na 50 (podniesienie do minimum)

*(proste)*

In [6]:
grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])

oceny_wysokie = grades[grades >= 80]
oceny_niedostateczne = grades[grades < 50]
oceny_w_przedziale = np.sum((grades >= 60) & (grades < 80))

zmienione_oceny = np.copy(grades)
zmienione_oceny = np.clip(zmienione_oceny, 50, None)

print(f"""
Oceny wysokie (>= 80): {oceny_wysokie}
Oceny niedostateczne (< 50): {oceny_niedostateczne}
Liczba ocen w przedziale [60, 80): {oceny_w_przedziale}
Oceny po podniesieniu do minimum 50: {zmienione_oceny}
""")


Oceny wysokie (>= 80): [92 88 91 85 95]
Oceny niedostateczne (< 50): [45 34 23]
Liczba ocen w przedziale [60, 80): 3
Oceny po podniesieniu do minimum 50: [78 50 92 67 50 88 56 91 50 85 73 95]



### Zadanie 7 — Tworzenie macierzy specjalnych

Utwórz następujące macierze:
- Macierz 3x3 wypełnioną zerami
- Macierz 4x4 wypełnioną jedynkami
- Macierz identyczności 5x5
- Macierz 3x4 wypełnioną liczbą 7
- Wektor 10 równoodległych wartości od 0 do 1

**Wymagania:**
- Użyj `np.zeros`, `np.ones`, `np.eye`, `np.full`, `np.linspace`

*(proste)*

### Zadanie 8 — Reshape i flatten

Dana tablica:
```python
arr = np.arange(1, 13)
```

Wykonaj:
- Zmień kształt na (3, 4)
- Zmień kształt na (2, 6)
- Zmień kształt na (4, 3)
- Spłaszcz z powrotem do 1D (flatten lub ravel)

**Wymagania:**
- Użyj metody `.reshape()`
- Sprawdź różnicę między `flatten()` a `ravel()`

*(proste)*

## ✏️ Zadania średnie (9–12)

### Zadanie 9 — Normalizacja danych

Dataset: Oceny z 3 przedmiotów dla 20 studentów
```python
scores = np.random.randint(40, 100, size=(20, 3))
```

**Wymagania:**
- Zastosuj normalizację Min-Max per przedmiot (kolumna) → [0, 1]
- Sprawdź, że min=0 i max=1 dla każdego przedmiotu
- Wizualizuj rozkład przed i po normalizacji (histogramy)

**Oczekiwany rezultat:**
- Tablica znormalizowana
- 2 histogramy (przed/po)

*(średnie)*

### Zadanie 10 — Broadcasting w praktyce

Dana tablica ocen (5 studentów x 4 egzaminy):
```python
exams = np.array([
    [78, 85, 92, 88],
    [65, 72, 68, 70],
    [90, 88, 95, 92],
    [55, 60, 58, 62],
    [82, 79, 85, 80]
])
```

Dodaj bonus do każdego egzaminu: `[5, 10, 5, 10]`

Następnie pomnóż wyniki każdego studenta przez mnożnik: `[1.0, 1.1, 0.95, 1.15, 1.0]`

**Wymagania:**
- Użyj broadcastingu (bez pętli)
- Wypisz wyniki przed i po

*(średnie)*

In [10]:
exams = np.array([
    [78, 85, 92, 88],
    [65, 72, 68, 70],
    [90, 88, 95, 92],
    [55, 60, 58, 62],
    [82, 79, 85, 80]
])

bonus = np.array([5, 10, 5, 10])
exams_w_bonus = np.copy(exams)
exams_w_bonus = exams_w_bonus + bonus

mnoznik = np.array([1.0, 1.1, 0.95, 1.15, 1.0])
exams_mnozone = exams_w_bonus * mnoznik.reshape(5, 1)

print("Wyniki przed dodaniem bonusu:\n", exams)
print("\nWyniki po dodaniu bonusu:\n", exams_w_bonus)
print("\nWyniki po dodaniu bonusu i zastosowaniu mnożnika:\n", exams_mnozone)

Wyniki przed dodaniem bonusu:
 [[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]

Wyniki po dodaniu bonusu:
 [[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]

Wyniki po dodaniu bonusu i zastosowaniu mnożnika:
 [[83.00 95.00 97.00 98.00]
 [77.00 90.20 80.30 88.00]
 [90.25 93.10 95.00 96.90]
 [69.00 80.50 72.45 82.80]
 [87.00 89.00 90.00 90.00]]


### Zadanie 11 — Analiza datasetu sprzedaży

Dataset: Sprzedaż 6 produktów w 30 dni
```python
sales = np.random.randint(50, 200, size=(6, 30))
```

Oblicz:
- Trend sprzedaży per produkt (różnica między ostatnimi 7 dniami a pierwszymi 7 dniami)
- Najlepszy tydzień (dni 0-6, 7-13, 14-20, 21-27) dla całej sprzedaży
- Wykres: sprzedaż per produkt w czasie (linie)

**Wymagania:**
- Użyj slicingu do wycinania tygodni
- Wizualizacja matplotlib

*(średnie)*

### Zadanie 12 — Odległość Euklidesowa

Masz 2 punkty w przestrzeni 5-wymiarowej:
```python
point_a = np.array([1, 2, 3, 4, 5])
point_b = np.array([5, 4, 3, 2, 1])
```

Oblicz odległość Euklidesową: `sqrt(sum((a - b)^2))`

Następnie oblicz macierz odległości dla 4 punktów:
```python
points = np.random.rand(4, 5)
```

**Wymagania:**
- Ręczna implementacja (bez gotowych funkcji)
- Wynik: macierz 4x4 odległości między każdą parą punktów

*(średnie)*

## 🧠 Zadania wyzwanie (13–20)

### Zadanie 13 — Standaryzacja i outliers

Dataset: 100 wartości z rozkładu normalnego + 5 outliers
```python
np.random.seed(42)
data = np.concatenate([np.random.randn(100) * 10 + 50,
                       np.array([150, -50, 200, -100, 180])])
np.random.shuffle(data)
```

**Wymagania:**
- Zastosuj standaryzację (z-score)
- Wykryj outliery (wartości z |z-score| > 3)
- Usuń outliery i ponownie standaryzuj
- Wizualizuj: przed/po (histogramy + box plot)

**Oczekiwany rezultat:**
- Tablica bez outlierów
- Wizualizacje pokazujące efekt

*(challenge)*

### Zadanie 14 — Symulacja Monte Carlo

Oszacuj wartość π metodą Monte Carlo:
- Generuj 1 000 000 losowych punktów (x, y) w kwadracie [-1, 1] x [-1, 1]
- Zlicz ile punktów znajduje się w kole (x² + y² <= 1)
- π ≈ 4 * (liczba w kole / liczba total)

**Wymagania:**
- Użyj `np.random.rand()` i operacji wektorowych
- Bez pętli (tylko NumPy)
- Wizualizuj pierwsze 10 000 punktów (kolor: w kole/poza kołem)

**Oczekiwany rezultat:**
- Oszacowanie π (powinno być ~3.14)
- Scatter plot

*(challenge)*

### Zadanie 15 — Convolution 1D (ręczna implementacja)

Dana tablica (sygnał) i kernel (filtr):
```python
signal = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
kernel = np.array([0.2, 0.6, 0.2])  # Średnia ruchoma
```

Zaimplementuj ręcznie konwolucję 1D (bez `np.convolve`):
- Dla każdej pozycji w sygnale zastosuj kernel
- Wynik: wygładzony sygnał

**Wymagania:**
- Użyj pętli tylko po pozycjach, operacje na kernelu wektorowe
- Wizualizuj: oryginalny sygnał vs wygładzony

*(challenge)*

### Zadanie 16 — Matrix multiplication (dot product)

Masz 2 macierze reprezentujące dane:
```python
A = np.random.rand(100, 50)  # 100 próbek, 50 cech
B = np.random.rand(50, 20)   # 50 cech → 20 cech (transformacja)
```

**Wymagania:**
- Wykonaj mnożenie macierzy: C = A @ B
- Zmierz czas operacji
- Porównaj z ręczną implementacją (3 zagnieżdżone pętle)
- Wypisz przyspieszenie NumPy

**Oczekiwany rezultat:**
- Macierz C (100, 20)
- Porównanie czasów

*(challenge)*

### Zadanie 17 — Image processing basics

Utwórz obraz (tablica 100x100) z losowymi wartościami [0, 255]:
```python
image = np.random.randint(0, 256, size=(100, 100), dtype=np.uint8)
```

Zastosuj:
- Progowanie (thresholding): piksele < 128 → 0, >= 128 → 255
- Negatyw: 255 - image
- Padding: dodaj ramkę 10 pikseli (zerami) dookoła obrazu

**Wymagania:**
- Użyj boolean indexing i `np.pad()`
- Wizualizuj: oryginalny, progowany, negatyw, z paddingiem

*(challenge)*

### Zadanie 18 — k-Nearest Neighbors (distance matrix)

Dataset: 50 punktów w 2D
```python
np.random.seed(10)
data = np.random.rand(50, 2) * 100
```

Dla nowego punktu `query = np.array([50, 50])`:
- Oblicz odległości od wszystkich 50 punktów (Euklidesowa)
- Znajdź 5 najbliższych sąsiadów (indeksy i odległości)
- Wizualizuj: scatter plot z zaznaczeniem query i 5-NN

**Wymagania:**
- Broadcasting do obliczenia wszystkich odległości jednocześnie
- `np.argsort()` do znalezienia najbliższych

*(challenge)*

### Zadanie 19 — Polynomial regression data preparation

Dataset: y = 2x² - 3x + 5 + noise
```python
x = np.linspace(0, 10, 100)
y = 2 * x**2 - 3 * x + 5 + np.random.randn(100) * 10
```

Przygotuj macierz cech dla regresji wielomianowej stopnia 2:
X = [1, x, x²]

**Wymagania:**
- Utwórz macierz X (100, 3): kolumny [1s, x, x²]
- Użyj `np.column_stack()` lub broadcasting
- Wizualizuj: scatter (x, y) + idealna parabola

**Oczekiwany rezultat:**
- Macierz X gotowa do regresji
- Wykres danych

*(challenge)*

### Zadanie 20 — Batch normalization simulation

Dataset: Mini-batch 32 próbek x 10 cech
```python
batch = np.random.randn(32, 10) * 5 + 20
```

Zastosuj Batch Normalization:
- Oblicz mean i std per cecha (axis=0)
- Standaryzuj: (batch - mean) / std
- Zastosuj scale i shift: gamma * batch_norm + beta (gamma=2, beta=1 dla wszystkich cech)

**Wymagania:**
- Użyj broadcasting
- Sprawdź statystyki przed i po
- Wykres: rozkład pierwotny vs znormalizowany (dla 1 cechy)

**Oczekiwany rezultat:**
- Batch po normalizacji i transformacji
- Histogramy przed/po

*(challenge)*